### ISSUE TITLE
2.7.1: TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'via_device_id'. Did you mean 'via_device'?

### ISSUE THREAD

**Issue by skrude61** [kamaradclimber/heishamon-homeassistant#398]
** Versions **

- Home Assistant version: 2026.6.3
- This integration version: 2.7.1

**Describe the bug**

With version 2.7.1 Home Assistant Log shows:
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'via_device_id'. Did you mean 'via_device'?

**To Reproduce**
1. Update to version 2.7.1
2. Click on 'Settings -> System -> Logs'
3. See error

**Comment by kamaradclimber** [comment]
Hello, thanks for reporting this issue.

Last release (2.7.1) requires home-assistant 2026.8.0 which introduces the `via_device_id` argument. I think the error you see is expected if you use a home-assistant older than this. I would expect hacs not to propose you the upgrade though 🤔 , are you using hacs to manage upgrades?

**Comment by skrude61** [comment]
I was using Home Assistant 2026.6.3 and yes, I'm using hacs. How does hacs know the required Home Assistant version?
BTW: After upgrading HA to 2026.9.1, the problem has gone.

**Comment by kamaradclimber** [comment]
hacs is supposed to respect https://github.com/kamaradclimber/heishamon-homeassistant/blob/main/hacs.json#L4 to not propose an update on incompatible HA version. Weird!

Since the issue has a solution, I'll close it. I really appreciate you opened an issue and a PR to fix it though ! 🙇
